spring:
  application:
    name: MASTER-APP
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-request-size: 1GB
      max-file-size: 1GB
server:
  port: 8080
api:
  endpoint:
    base-url: /api/v1
khmerlang:
  client:
    base-url: https://api.khmerlang.com/v1/word-segmentation
